### ISSUE TITLE
 Xanitizer XML report file not found

### ISSUE THREAD

**Issue by hugoploeg** [RIGS-IT/sonar-xanitizer#4]
Hello

We are running SonarQube 5.6.6 (LTS *) with the plugin Xanitizer 3.3 and that is all running on Centos. The jobs are set on jenkins and that is the trigger to run the test.

The jobs are running perfect true jenkins only Im trying to fix it with the Xanitizer plugin. Below the it keeps given the following error. Already tried an earlyer version of the plugin doesn't fix it. Does someone know how to fix this? Looks like he is not generating the Xanitizer-Findings-List.xml

15:08:48.393 WARN - Xanitizer XML report file '/var/lib/jenkins/jobs/SONAR-QUALITY/workspace/Xanitizer-Findings-List.xml' not found. Skipping analysis.

How can I fix the XML path?

Regards, Hugo

**Comment by normanwenzel** [comment]
Hello Hugo,

so you try to run the Xanitizer plugin, but don't have created the XML-file before, is this correct?

The plugin is NO standalone tool. It INTEGRATES the results of the Xanitizer security analysis tool into SonarQube. So what you have to do is to create the report with the main tool (either from the GUI or by running a headless analysis task) and then THIS report file is used as an input for the SonarQube plugin.
If you havent't yet installed the Xanitizer main tool, you can get it here for free: https://www.rigs-it.net/index.php/get-xanitizer.html

Many regards
Norman

**Comment by hugoploeg** [comment]
Hello Norman,

>so you try to run the Xanitizer plugin, but don't have created the XML-file before, is this 
correct?

Indeed I don't have created the XML-file, but I think I Understand it already :).
Is there some kind of documentation for how to  run the headless analysis Task? Im running the sonar cube on Centos 7.

Regards,

**Comment by normanwenzel** [comment]
You can find a detailed documentation of the headless mode in the Xanitizer user manual (chapter 3).

Btw: I would expect that you did not have received the download links... it looks like there is a typo in your mail address (just ending on .om instead of .com), so I would advice you to send another request ;)

**Comment by hugoploeg** [comment]
Ok, thanks Norman. Ik have received the download links now.

Regards,
Hugo
