### ISSUE TITLE
Plugin does not load in SonarQube LTS 6.7.1

### ISSUE THREAD

**Issue by jackperalta** [RIGS-IT/sonar-xanitizer#7]
When installing the plugin in SonarQube LTS 6.7.1 it does not seem to be installed.

After restarting sonarqube, there is no settings area available for the plugin as described here. 

in the log it shows as deployed

`2018.02.08 08:47:53 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Xanitizer / 1.5.0
`

**Comment by normanwenzel** [comment]
Hello Jack,

is it possible that you are looking at the wrong settings? The plugin is configured in the settings area of a project, not in the global settings.
Is the plugin listed under "Installed Plugins" in the Update Center?

Many regards
Norman

**Comment by jackperalta** [comment]
Hi Norman,

my bad - you are right - I simply looked at the wrong place...

thanks for clarification
